import axios from 'axios'

// Generated by https://quicktype.io

export interface IPost {
    createdAt: string
    title: string
    body: string
    tags: string
    id: string
    reactions: string
    poster: string
}

export default class PostService {
    static async getAll() {
        const { data } = await axios.get<IPost[]>(`https://647dab38af984710854a1762.mockapi.io/post`)
        return data.reverse()
    }
    static async addOne(data: any) {
        console.log(data)
    }
}
